# Generated by Django 5.0.4 on 2024-04-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_finishedtraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.PositiveSmallIntegerField(verbose_name='Подход')),
                ('weight', models.PositiveSmallIntegerField(null=True, verbose_name='Вес')),
                ('repetitions', models.PositiveSmallIntegerField(verbose_name='Повторений')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.finishedtraining')),
            ],
            options={
                'verbose_name': 'Выполненный подход',
                'verbose_name_plural': 'Выполненные подходы',
            },
        ),
    ]
