# Generated by Django 5.0.4 on 2024-05-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_finishedexerciseset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='finishedtraining',
            options={'ordering': ('-started_at',), 'verbose_name': 'Выполненная тренировка', 'verbose_name_plural': 'Выполненные тренировки'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.training'),
        ),
        migrations.AlterField(
            model_name='finishedtraining',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Финиш'),
        ),
        migrations.AlterField(
            model_name='finishedtraining',
            name='started_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Старт'),
        ),
        migrations.AlterField(
            model_name='finishedtraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_trainings', to='main.training'),
        ),
    ]
