# Generated by Django 5.0.4 on 2024-06-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_finishedtraining_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedRunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
