# Generated by Django 5.0.4 on 2024-06-04 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_finishedrunning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedrunning',
            options={'verbose_name': 'Выполненная пробежка', 'verbose_name_plural': 'Выполненные пробежки'},
        ),
        migrations.AddField(
            model_name='finishedrunning',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Финиш'),
            preserve_default=False,
        ),
    ]
